export const CURRENTLY_ATTEMPTING_PUT = 'CURRENTLY_ATTEMPTING_PUT';
export const PUT_SOCIAL_REACH_INFO_SUCCESS = 'PUT_SOCIAL_REACH_INFO_SUCCESS';
export const PUT_SOCIAL_REACH_INFO_FAIL = 'PUT_SOCIAL_REACH_INFO_FAIL';
